# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/react/vitest-inside-jsx-component"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vue/nuxt-fullstack-realworld"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vue/ts-no-infer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vue/vitest-inside-jsx-component"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/rust/rust-api-example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/rust/yew-playground"
    schedule:
      interval: "weekly"
